spring:
  config:
    activate:
      on-profile: dev
---
server:
  port: 8080
  servlet:
    contextPath: /api
---
spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/user}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:Khai2604@}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
---
open:
  api:
    title: API Backend Docs
    version: v1.0.0
    description: Meta API services
    serverUrl: http://localhost:8080
    serverName: development server
---
jwt:
  privateKey: classpath:private.pem
  publicKey: classpath:public.pem


