spring:
  config:
    activate:
      on-profile: dev
---
server:
  port: 8080
  servlet:
    contextPath: /api
---
spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/homestay_booking}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:Khai2604@}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  servlet:
    multipart:
      max-file-size: 100MB
---
file:
  max-file-size: 2097152  # 1 * 1024 * 1024 1MB
---
jwt:
  privateKey: classpath:private.pem
  publicKey: classpath:public.pem
  expiration:
    access-token: 8000
    refresh-token: 10000
---
logging:
  file:
    name: app.log
---
cors:
  allowed:
    origins: ${FRONT_END_URL:http://localhost:5173}
---
payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    returnUrl: http://localhost:8080/api/payment/vn-pay-callback
    tmnCode: JMEGBUDB
    secretKey: 89Q7V4XP8PJDURBR4MX03YNL0K0C7CGD
    version: 2.1.0
    command: pay
    orderType: other




